curl https://editor.p5js.org/editor/projects/7hzeHDSIl/zip -o "downloads/zips/03-jht-hatviz.zip"
curl https://editor.p5js.org/editor/projects/AnDswZ6eY/zip -o "downloads/zips/1.2 draw_shapes_ui.zip"
curl https://editor.p5js.org/editor/projects/-QATBkoGr/zip -o "downloads/zips/10PRINT copy.zip"
curl https://editor.p5js.org/editor/projects/a0HDzoroq/zip -o "downloads/zips/11.3: The Pixel Array.zip"
curl https://editor.p5js.org/editor/projects/ixSKM5gnT/zip -o "downloads/zips/11.3: The Pixel Array - p5.js Tutorial.zip"
curl https://editor.p5js.org/editor/projects/-bPa6T0T3/zip -o "downloads/zips/11.3: The Pixel Array Slider copy.zip"
curl https://editor.p5js.org/editor/projects/tdqHhMrIH/zip -o "downloads/zips/11.3: The Pixel Array Slider copy.zip"
curl https://editor.p5js.org/editor/projects/1DfZ5dRU1/zip -o "downloads/zips/11.4 Brightness Mirror.zip"
curl https://editor.p5js.org/editor/projects/J7Zhes2Tc/zip -o "downloads/zips/11.4: Brightness getpixel.zip"
curl https://editor.p5js.org/editor/projects/sd8fP5xtL/zip -o "downloads/zips/11.6 Painting with Pixels.zip"
curl https://editor.p5js.org/editor/projects/-imqZQyIkv/zip -o "downloads/zips/17.11_FFT ui - funky.zip"
curl https://editor.p5js.org/editor/projects/Y2LMO3xGx/zip -o "downloads/zips/17.8: Microphone Input.zip"
curl https://editor.p5js.org/editor/projects/CpRGKpB2X/zip -o "downloads/zips/17.9_graphingAmplitude copy.zip"
curl https://editor.p5js.org/editor/projects/rXhPgZ1k6/zip -o "downloads/zips/2.2.3 circleX width ui.zip"
curl https://editor.p5js.org/editor/projects/Av1a8fSj4/zip -o "downloads/zips/2.2.3 circleX width ui local vars.zip"
curl https://editor.p5js.org/editor/projects/DfGSm6IZH/zip -o "downloads/zips/2.2.3 circleX width ui v1 object literal.zip"
curl https://editor.p5js.org/editor/projects/Rl63Kstm0/zip -o "downloads/zips/2.2.3 circleX width ui v2.zip"
curl https://editor.p5js.org/editor/projects/1OY9mWiG4/zip -o "downloads/zips/3.4_1_p5.js_Boolean_variables.zip"
curl https://editor.p5js.org/editor/projects/kYQnnCtQr/zip -o "downloads/zips/3.4_1_p5.js_Boolean_variables copy.zip"
curl https://editor.p5js.org/editor/projects/K49FS1RJL/zip -o "downloads/zips/3.4_1_p5.js_Boolean_variables copy copy.zip"
curl https://editor.p5js.org/editor/projects/yQr7TCMaE/zip -o "downloads/zips/3.4_1_p5.js_Boolean_variables copy copy copy.zip"
curl https://editor.p5js.org/editor/projects/mw9zNJ2EA/zip -o "downloads/zips/3.4_1_p5.js_Boolean_variables copy copy copy copy.zip"
curl https://editor.p5js.org/editor/projects/bG2JhGUBX/zip -o "downloads/zips/3.5 circleX a_len ui.zip"
curl https://editor.p5js.org/editor/projects/h64xxtnIM/zip -o "downloads/zips/3.5 circleX slider.zip"
curl https://editor.p5js.org/editor/projects/UYiQ_IKf2/zip -o "downloads/zips/3.5 DOM Kit slider checkbox select.zip"
curl https://editor.p5js.org/editor/projects/IwaHqYnDn/zip -o "downloads/zips/7.3 Arrays of objects 1 copy.zip"
curl https://editor.p5js.org/editor/projects/wOBMJbldS/zip -o "downloads/zips/Acceleration Ball Bounce.zip"
curl https://editor.p5js.org/editor/projects/Rdb_xgkkW/zip -o "downloads/zips/acceleration-scope.zip"
curl https://editor.p5js.org/editor/projects/RRtBxe8lI/zip -o "downloads/zips/accelerationXYZ.zip"
curl https://editor.p5js.org/editor/projects/fpytkwPBO/zip -o "downloads/zips/assignment week 3 copy.zip"
curl https://editor.p5js.org/editor/projects/fuvgc14Jh/zip -o "downloads/zips/Assignment_W3_3 copy copy.zip"
curl https://editor.p5js.org/editor/projects/dxElfI0pB/zip -o "downloads/zips/async-await-setTimeout.zip"
curl https://editor.p5js.org/editor/projects/D5NJlDzOC/zip -o "downloads/zips/Beaded scorpio.zip"
curl https://editor.p5js.org/editor/projects/JDCmTP9Wv/zip -o "downloads/zips/Bedecked kangaroo copy.zip"
curl https://editor.p5js.org/editor/projects/nEtIPPdvM/zip -o "downloads/zips/Bouncing Ball copy.zip"
curl https://editor.p5js.org/editor/projects/1uFrAUdQF/zip -o "downloads/zips/Breezy packet.zip"
curl https://editor.p5js.org/editor/projects/q2b4jtO-C/zip -o "downloads/zips/chat-G gen art.zip"
curl https://editor.p5js.org/editor/projects/vYQa-C5RP/zip -o "downloads/zips/chat-G gen art rev.zip"
curl https://editor.p5js.org/editor/projects/DHz0bVV1z/zip -o "downloads/zips/chat-G gen art rev 2.zip"
curl https://editor.p5js.org/editor/projects/GWlHB700H/zip -o "downloads/zips/chat-G gen art rev3.zip"
curl https://editor.p5js.org/editor/projects/pUygFBDh8/zip -o "downloads/zips/chat-G pong.zip"
curl https://editor.p5js.org/editor/projects/wEuVbyycj/zip -o "downloads/zips/chat-G pong pause.zip"
curl https://editor.p5js.org/editor/projects/KfLHXuwlr/zip -o "downloads/zips/chat-G pong pause fix.zip"
curl https://editor.p5js.org/editor/projects/y8_gBGVUS/zip -o "downloads/zips/chat-G Scratch risk.zip"
curl https://editor.p5js.org/editor/projects/VB_EmgNTF/zip -o "downloads/zips/checking objects intersection.zip"
curl https://editor.p5js.org/editor/projects/57DXiQJnK/zip -o "downloads/zips/circleX buttons copy.zip"
curl https://editor.p5js.org/editor/projects/14JGoHqT7/zip -o "downloads/zips/circleX circleY copy.zip"
curl https://editor.p5js.org/editor/projects/YzWb1TTnA/zip -o "downloads/zips/circleX circleY copy.zip"
curl https://editor.p5js.org/editor/projects/ZHq9Gwmnx/zip -o "downloads/zips/circleX circleY copy.zip"
curl https://editor.p5js.org/editor/projects/qmtBJEwMe/zip -o "downloads/zips/circleX follow copy.zip"
curl https://editor.p5js.org/editor/projects/HkG6bo5KG/zip -o "downloads/zips/circleX modulo copy.zip"
curl https://editor.p5js.org/editor/projects/2k5Hx3nNi/zip -o "downloads/zips/colorMode-rainbow.zip"
curl https://editor.p5js.org/editor/projects/-YsCNS7L7/zip -o "downloads/zips/colorMode-rainbow copy.zip"
curl https://editor.p5js.org/editor/projects/wLcXnn1R_/zip -o "downloads/zips/colorMode-rainbow-flag.zip"
curl https://editor.p5js.org/editor/projects/IQ8NRl6C8/zip -o "downloads/zips/colorMode-rainbow-single.zip"
curl https://editor.p5js.org/editor/projects/O2Pgf8nC5/zip -o "downloads/zips/console.log frameCount.zip"
curl https://editor.p5js.org/editor/projects/MMqtOoRnS/zip -o "downloads/zips/Cultivate digit.zip"
curl https://editor.p5js.org/editor/projects/D1lGG8qKZ/zip -o "downloads/zips/Cultivate digit copy.zip"
curl https://editor.p5js.org/editor/projects/Fq7pag-yO/zip -o "downloads/zips/day1.zip"
curl https://editor.p5js.org/editor/projects/XH_F8U6iN/zip -o "downloads/zips/Day1-pattern-grid.zip"
curl https://editor.p5js.org/editor/projects/Ll9Kd-9Ec/zip -o "downloads/zips/Day2-matching-bounce.zip"
curl https://editor.p5js.org/editor/projects/vEMkKSM1s/zip -o "downloads/zips/Day2-matching-game.zip"
curl https://editor.p5js.org/editor/projects/A25CBlLTl/zip -o "downloads/zips/Day2-matching-move.zip"
curl https://editor.p5js.org/editor/projects/BDNT4XMEU/zip -o "downloads/zips/Day2-pattern-image.zip"
curl https://editor.p5js.org/editor/projects/6Y5QBwf8n/zip -o "downloads/zips/Day4-slides.zip"
curl https://editor.p5js.org/editor/projects/wR2zhKdWw/zip -o "downloads/zips/Day5-matching.zip"
curl https://editor.p5js.org/editor/projects/Yhxxthfo1/zip -o "downloads/zips/Day5-matching emoji.zip"
curl https://editor.p5js.org/editor/projects/pLglN2W9N/zip -o "downloads/zips/Day5-matching emoji array.zip"
curl https://editor.p5js.org/editor/projects/vDU04Lua2/zip -o "downloads/zips/Day5-matching emoji copy.zip"
curl https://editor.p5js.org/editor/projects/By5uOrJQF/zip -o "downloads/zips/Day5-matching emoji mobile.zip"
curl https://editor.p5js.org/editor/projects/KkogwpxYy/zip -o "downloads/zips/Day5-matching random.zip"
curl https://editor.p5js.org/editor/projects/-5qcnnr2L/zip -o "downloads/zips/draw sine wave.zip"
curl https://editor.p5js.org/editor/projects/bJwxdGIpX/zip -o "downloads/zips/draw-rainbow.zip"
curl https://editor.p5js.org/editor/projects/fEp51pBhA/zip -o "downloads/zips/draw-share.zip"
curl https://editor.p5js.org/editor/projects/mCr2W68mc/zip -o "downloads/zips/draw-share-multi.zip"
curl https://editor.p5js.org/editor/projects/L5Vr53NQl/zip -o "downloads/zips/draw-video.zip"
curl https://editor.p5js.org/editor/projects/q14Kn5a0O/zip -o "downloads/zips/earth-lat-lon.zip"
curl https://editor.p5js.org/editor/projects/bpsB_xmSH/zip -o "downloads/zips/earth-xyz.zip"
curl https://editor.p5js.org/editor/projects/5Y1WTyVd-/zip -o "downloads/zips/Fancy Pong Chords.zip"
curl https://editor.p5js.org/editor/projects/difxyfpEa/zip -o "downloads/zips/Fancy Pong collision.zip"
curl https://editor.p5js.org/editor/projects/casPMQqcA/zip -o "downloads/zips/Fancy Pong copy.zip"
curl https://editor.p5js.org/editor/projects/QB13gST05/zip -o "downloads/zips/Fancy Pong Things.zip"
curl https://editor.p5js.org/editor/projects/aY6BqcsGh/zip -o "downloads/zips/Fibonacci sequence (visualisation) by ktorn -- jht remix.zip"
curl https://editor.p5js.org/editor/projects/Eek-GafQr/zip -o "downloads/zips/Fibonacci sequence (visualisation) by ktorn -- jht remix copy.zip"
curl https://editor.p5js.org/editor/projects/x7bG2j2xZ/zip -o "downloads/zips/Fibonacci sequence (visualisation) by ktorn -- jht remix Object Literal version.zip"
curl https://editor.p5js.org/editor/projects/ncIe7u-WC/zip -o "downloads/zips/Firebase-createImg-board copy.zip"
curl https://editor.p5js.org/editor/projects/4DETmJP-l/zip -o "downloads/zips/foo error.zip"
curl https://editor.p5js.org/editor/projects/I1Ml-NlCE/zip -o "downloads/zips/Fourier-Elephant-Lower-frequencies copy.zip"
curl https://editor.p5js.org/editor/projects/Y_8087I5S/zip -o "downloads/zips/Full Scan XY.zip"
curl https://editor.p5js.org/editor/projects/l3ELOjGdJ/zip -o "downloads/zips/Game States.zip"
curl https://editor.p5js.org/editor/projects/6HRN2MYyH/zip -o "downloads/zips/Game States array.zip"
curl https://editor.p5js.org/editor/projects/AhJPcoZde/zip -o "downloads/zips/Game States array buttons.zip"
curl https://editor.p5js.org/editor/projects/-eVVn0lh2/zip -o "downloads/zips/Game States explicit.zip"
curl https://editor.p5js.org/editor/projects/W8Do-exuT/zip -o "downloads/zips/Garrulous amphibian.zip"
curl https://editor.p5js.org/editor/projects/DRpj2TQRg/zip -o "downloads/zips/geolocation.zip"
curl https://editor.p5js.org/editor/projects/hzQ_IGYd8/zip -o "downloads/zips/global variable pattern animation.zip"
curl https://editor.p5js.org/editor/projects/NeWYQtl2J/zip -o "downloads/zips/hello-p5-song.zip"
curl https://editor.p5js.org/editor/projects/wxcIn0BaK/zip -o "downloads/zips/ICM - WK6 - practicing with objects copy.zip"
curl https://editor.p5js.org/editor/projects/rpyY0uqRR/zip -o "downloads/zips/ICM 2023 jht student selector.zip"
curl https://editor.p5js.org/editor/projects/6L3aL1OEy/zip -o "downloads/zips/ICM jht student selector textarea.zip"
curl https://editor.p5js.org/editor/projects/tOvM0opxr/zip -o "downloads/zips/ICM Week 1 Assignment - Self Portrait.zip"
curl https://editor.p5js.org/editor/projects/bxKaEtXBv/zip -o "downloads/zips/ICM Week 1 Assignment - Self Portrait copy.zip"
curl https://editor.p5js.org/editor/projects/Wkl-MS8LU/zip -o "downloads/zips/ICM Week 1 Assignment - Self Portrait copy.zip"
curl https://editor.p5js.org/editor/projects/JH6A8CFo2/zip -o "downloads/zips/ICM_W1_HW_QZ658 copy.zip"
curl https://editor.p5js.org/editor/projects/0OHUgo_c6/zip -o "downloads/zips/image  array sin.zip"
curl https://editor.p5js.org/editor/projects/mx-4OoEkk/zip -o "downloads/zips/Image Drawing copy.zip"
curl https://editor.p5js.org/editor/projects/P-AHc4NF9/zip -o "downloads/zips/image preload  array.zip"
curl https://editor.p5js.org/editor/projects/X4B7LH5Xj/zip -o "downloads/zips/image preload  copy4.zip"
curl https://editor.p5js.org/editor/projects/rKzf_JMBB/zip -o "downloads/zips/image preload copy2.zip"
curl https://editor.p5js.org/editor/projects/ozUZXTjie/zip -o "downloads/zips/image preload rh.zip"
curl https://editor.p5js.org/editor/projects/H4XTYK58S/zip -o "downloads/zips/images puzzle.zip"
curl https://editor.p5js.org/editor/projects/aNEAWxDCN/zip -o "downloads/zips/images puzzle copy.zip"
curl https://editor.p5js.org/editor/projects/1T6gctA4_/zip -o "downloads/zips/images puzzle grid.zip"
curl https://editor.p5js.org/editor/projects/Sgh9j2tCz/zip -o "downloads/zips/images shuffle.zip"
curl https://editor.p5js.org/editor/projects/6GTcx_Ia6/zip -o "downloads/zips/images shuffle iOS.zip"
curl https://editor.p5js.org/editor/projects/G4K2yaPnz/zip -o "downloads/zips/IMS - Truchet Vamoss copy.zip"
curl https://editor.p5js.org/editor/projects/CYMdD77ySc/zip -o "downloads/zips/ims-03-jht truchet tiles pause copy.zip"
curl https://editor.p5js.org/editor/projects/3VKJ-q8ar/zip -o "downloads/zips/ims03-jht scrolling color bars.zip"
curl https://editor.p5js.org/editor/projects/ZGUqiovgG/zip -o "downloads/zips/ims03-jht scrolling color time.zip"
curl https://editor.p5js.org/editor/projects/hmwAqitsO/zip -o "downloads/zips/input DOM element method.zip"
curl https://editor.p5js.org/editor/projects/-P_lpGf16/zip -o "downloads/zips/Invincible shame.zip"
curl https://editor.p5js.org/editor/projects/j4tQqgSxZ/zip -o "downloads/zips/jht preload  imgs.zip"
curl https://editor.p5js.org/editor/projects/jms7R-njY/zip -o "downloads/zips/let draw  pattern.zip"
curl https://editor.p5js.org/editor/projects/76kBiMBMU/zip -o "downloads/zips/let me variable pattern animation.zip"
curl https://editor.p5js.org/editor/projects/cCVbcQ5KU/zip -o "downloads/zips/let variables.zip"
curl https://editor.p5js.org/editor/projects/CTgQEzZU8/zip -o "downloads/zips/let variables draw.zip"
curl https://editor.p5js.org/editor/projects/2VtmNQgzJ/zip -o "downloads/zips/let variables topleft.zip"
curl https://editor.p5js.org/editor/projects/tnEPOHqIP/zip -o "downloads/zips/let variables topleft ellipse.zip"
curl https://editor.p5js.org/editor/projects/HzDuEq5B4/zip -o "downloads/zips/let variables while.zip"
curl https://editor.p5js.org/editor/projects/KdqhNNLLW/zip -o "downloads/zips/let variables while y1.zip"
curl https://editor.p5js.org/editor/projects/mupQOIvCw/zip -o "downloads/zips/many circles object literal.zip"
curl https://editor.p5js.org/editor/projects/ZKPaZOjf_/zip -o "downloads/zips/match pairs emoji.zip"
curl https://editor.p5js.org/editor/projects/qfMmYs2br/zip -o "downloads/zips/Melanie pong with object array.zip"
curl https://editor.p5js.org/editor/projects/_8fx3fhlQ/zip -o "downloads/zips/Melanie pong with object literals.zip"
curl https://editor.p5js.org/editor/projects/pwLiHkndo/zip -o "downloads/zips/mic graph.zip"
curl https://editor.p5js.org/editor/projects/7Wjlo3pPU/zip -o "downloads/zips/mo-pixel-grid.zip"
curl https://editor.p5js.org/editor/projects/MbS5C3j-F/zip -o "downloads/zips/Necessary-forgery-timed-drawing.zip"
curl https://editor.p5js.org/editor/projects/RMLnbEz8y/zip -o "downloads/zips/p5.Envelope setADSR.zip"
curl https://editor.p5js.org/editor/projects/fxKlGB30J/zip -o "downloads/zips/p5js Code! - 2.2 - make your own variable copy.zip"
curl https://editor.p5js.org/editor/projects/3n2FV2isn/zip -o "downloads/zips/p5js Code! - Array of Objects nmax.zip"
curl https://editor.p5js.org/editor/projects/m2QEs5a1SO/zip -o "downloads/zips/p5js Code! - createGraphics copy.zip"
curl https://editor.p5js.org/editor/projects/w6JdXyWak/zip -o "downloads/zips/p5js Code! - Mouse Interaction with Objects copy.zip"
curl https://editor.p5js.org/editor/projects/faJ17d4bK/zip -o "downloads/zips/p5js Code! - Nested Loops copy.zip"
curl https://editor.p5js.org/editor/projects/jQNDwKvPL/zip -o "downloads/zips/p5js Code! - The Bouncing Ball copy.zip"
curl https://editor.p5js.org/editor/projects/dSvAa8vCJ/zip -o "downloads/zips/p5js Code! - while and for Loops NO LOOP.zip"
curl https://editor.p5js.org/editor/projects/lqMJIQoIs/zip -o "downloads/zips/p5Live  many.zip"
curl https://editor.p5js.org/editor/projects/r7vUnwdUz/zip -o "downloads/zips/p5play-starter-code.zip"
curl https://editor.p5js.org/editor/projects/UePTr_GLf/zip -o "downloads/zips/p5play-tumbler.zip"
curl https://editor.p5js.org/editor/projects/R-l3T5FA4/zip -o "downloads/zips/Patch neem by bigmouthflower.zip"
curl https://editor.p5js.org/editor/projects/7cGhNLC0J/zip -o "downloads/zips/Patch neem by bigmouthflower -- jht9629-gmail remix copy.zip"
curl https://editor.p5js.org/editor/projects/SAXrZi2yd/zip -o "downloads/zips/pattern animation my_shape.zip"
curl https://editor.p5js.org/editor/projects/Xha1utfMM/zip -o "downloads/zips/pattern animation random colors.zip"
curl https://editor.p5js.org/editor/projects/uOky-JReN/zip -o "downloads/zips/pattern my_rect my_circle.zip"
curl https://editor.p5js.org/editor/projects/hdVwHgCem/zip -o "downloads/zips/pattern-animation random gary.zip"
curl https://editor.p5js.org/editor/projects/xPpK77F8_/zip -o "downloads/zips/pattern-animation random rgb.zip"
curl https://editor.p5js.org/editor/projects/IO8kA4nVt/zip -o "downloads/zips/pattern-animation random rz.zip"
curl https://editor.p5js.org/editor/projects/qGByTdQGf/zip -o "downloads/zips/pattern-animation rect ellipse.zip"
curl https://editor.p5js.org/editor/projects/kQ6k4eRXp/zip -o "downloads/zips/pattern-animation while.zip"
curl https://editor.p5js.org/editor/projects/YS8IXXEuP/zip -o "downloads/zips/pattern-animation-gray.zip"
curl https://editor.p5js.org/editor/projects/5vef5sInl/zip -o "downloads/zips/pattern-animation-gray while.zip"
curl https://editor.p5js.org/editor/projects/1Tc2xb_4m/zip -o "downloads/zips/pattern-animation-shape.zip"
curl https://editor.p5js.org/editor/projects/zVQJNjK8R/zip -o "downloads/zips/Physarum Letters -- jht remix.zip"
curl https://editor.p5js.org/editor/projects/BtTb0NzK9/zip -o "downloads/zips/pixel-center.zip"
curl https://editor.p5js.org/editor/projects/twgS6eWRZ/zip -o "downloads/zips/pixel-grid.zip"
curl https://editor.p5js.org/editor/projects/_0fWGg7ni/zip -o "downloads/zips/pixel-scope.zip"
curl https://editor.p5js.org/editor/projects/9gmJeI1t3/zip -o "downloads/zips/playingWithArcs.zip"
curl https://editor.p5js.org/editor/projects/pFVPjcFSr/zip -o "downloads/zips/PolySynth.zip"
curl https://editor.p5js.org/editor/projects/9Ss9owTn5/zip -o "downloads/zips/Pong Chaos startup mostly.zip"
curl https://editor.p5js.org/editor/projects/mMwCV6fhx/zip -o "downloads/zips/Pong Chords Chaos.zip"
curl https://editor.p5js.org/editor/projects/V726KL-v-/zip -o "downloads/zips/Pong Chords Chaos start.zip"
curl https://editor.p5js.org/editor/projects/sS-J8BKLT/zip -o "downloads/zips/Pong codingtrain.zip"
curl https://editor.p5js.org/editor/projects/ZaNW60Qcm/zip -o "downloads/zips/Pong drop.zip"
curl https://editor.p5js.org/editor/projects/Oin13AMrB/zip -o "downloads/zips/Pong drop earth-xyz.zip"
curl https://editor.p5js.org/editor/projects/al6qh_HwA/zip -o "downloads/zips/preload data url.zip"
curl https://editor.p5js.org/editor/projects/Q5q1_WZVS/zip -o "downloads/zips/preload loadImage.zip"
curl https://editor.p5js.org/editor/projects/uGJhjABpY/zip -o "downloads/zips/preload loadImage scale.zip"
curl https://editor.p5js.org/editor/projects/lNRQmapgz/zip -o "downloads/zips/Rainbow Canvas.zip"
curl https://editor.p5js.org/editor/projects/32_bqUtVh/zip -o "downloads/zips/real pong copy (day 3) copy.zip"
curl https://editor.p5js.org/editor/projects/dkTJsQsua/zip -o "downloads/zips/red-green-gold-flag.zip"
curl https://editor.p5js.org/editor/projects/G6Zr5SBuq/zip -o "downloads/zips/rotationX.zip"
curl https://editor.p5js.org/editor/projects/TXvXSJY6L/zip -o "downloads/zips/rotationXYZ.zip"
curl https://editor.p5js.org/editor/projects/uFdR26C9p/zip -o "downloads/zips/Rural sardine.zip"
curl https://editor.p5js.org/editor/projects/fgWtAlOV8/zip -o "downloads/zips/Scratched sputter.zip"
curl https://editor.p5js.org/editor/projects/JfRBSdz13/zip -o "downloads/zips/Scrawny cephalopod.zip"
curl https://editor.p5js.org/editor/projects/gvejCZKCv/zip -o "downloads/zips/setup shapes.zip"
curl https://editor.p5js.org/editor/projects/1dsvV3GAg/zip -o "downloads/zips/Shared Space 3D copy.zip"
curl https://editor.p5js.org/editor/projects/jMHNj7slF/zip -o "downloads/zips/show-video-draw.zip"
curl https://editor.p5js.org/editor/projects/VtRGiz_JI/zip -o "downloads/zips/show-video-draw-bounce.zip"
curl https://editor.p5js.org/editor/projects/JOLlK94B6/zip -o "downloads/zips/show-video-draw-bounce copy.zip"
curl https://editor.p5js.org/editor/projects/MsutfNZq-/zip -o "downloads/zips/show-video-face-ui.zip"
curl https://editor.p5js.org/editor/projects/uKHKJ1yqX/zip -o "downloads/zips/show-video-jitter.zip"
curl https://editor.p5js.org/editor/projects/oVJEGvodF/zip -o "downloads/zips/Simple Draw.zip"
curl https://editor.p5js.org/editor/projects/owix6hP8S/zip -o "downloads/zips/simple-draw.zip"
curl https://editor.p5js.org/editor/projects/hw8qkUuAw/zip -o "downloads/zips/Slit Scan.zip"
curl https://editor.p5js.org/editor/projects/hoDXxFN8l/zip -o "downloads/zips/Slit Scan Rotate.zip"
curl https://editor.p5js.org/editor/projects/n0LuBwifE/zip -o "downloads/zips/Slit Scan X.zip"
curl https://editor.p5js.org/editor/projects/2bzqKDQjg/zip -o "downloads/zips/Slit Scan X Save.zip"
curl https://editor.p5js.org/editor/projects/t28ukgaji/zip -o "downloads/zips/Slit Scan X-Y.zip"
curl https://editor.p5js.org/editor/projects/puf0Xe6j0/zip -o "downloads/zips/Slit Scan XY.zip"
curl https://editor.p5js.org/editor/projects/5lRcFyYHd/zip -o "downloads/zips/Slit Scan Y Save.zip"
curl https://editor.p5js.org/editor/projects/hpcNjIm7v/zip -o "downloads/zips/sound-note-envelope.zip"
curl https://editor.p5js.org/editor/projects/z6Sg4ZYU3/zip -o "downloads/zips/soundFile copy.zip"
curl https://editor.p5js.org/editor/projects/nH-IvlQGD/zip -o "downloads/zips/South coral.zip"
curl https://editor.p5js.org/editor/projects/7X1wo51f1/zip -o "downloads/zips/Spiny heat.zip"
curl https://editor.p5js.org/editor/projects/xM9WSCoMi/zip -o "downloads/zips/storinginput - from java.zip"
curl https://editor.p5js.org/editor/projects/6A3mSelw8/zip -o "downloads/zips/Stormy oviraptor.zip"
curl https://editor.p5js.org/editor/projects/6FRgWWxc_/zip -o "downloads/zips/Stupendous tellurium copy.zip"
curl https://editor.p5js.org/editor/projects/m_T2CwLIf/zip -o "downloads/zips/system variables width height.zip"
curl https://editor.p5js.org/editor/projects/gXevt_9j8/zip -o "downloads/zips/three video effects.zip"
curl https://editor.p5js.org/editor/projects/-t2O5JfBr/zip -o "downloads/zips/timed-drawing.zip"
curl https://editor.p5js.org/editor/projects/yEhwOiog5/zip -o "downloads/zips/timed-drawing-class.zip"
curl https://editor.p5js.org/editor/projects/lBrb1cBQ7/zip -o "downloads/zips/truchet tiles copy.zip"
curl https://editor.p5js.org/editor/projects/ghy_WpWDr/zip -o "downloads/zips/truchet tiles odd.zip"
curl https://editor.p5js.org/editor/projects/fWSv5uzke/zip -o "downloads/zips/truchet tiles pause copy.zip"
curl https://editor.p5js.org/editor/projects/1CpIVSqp_d/zip -o "downloads/zips/truchet tiles tweeked.zip"
curl https://editor.p5js.org/editor/projects/N5pj99g-N/zip -o "downloads/zips/two circles object literal.zip"
curl https://editor.p5js.org/editor/projects/aJkcqKahg/zip -o "downloads/zips/video meter rgb long.zip"
curl https://editor.p5js.org/editor/projects/sJM2AMf5T/zip -o "downloads/zips/video pixel.zip"
curl https://editor.p5js.org/editor/projects/p0ato8vra/zip -o "downloads/zips/video pixel meter.zip"
curl https://editor.p5js.org/editor/projects/HRjZBETUA/zip -o "downloads/zips/video pixel scan.zip"
curl https://editor.p5js.org/editor/projects/3ZwzK2buW/zip -o "downloads/zips/video pixel scan random.zip"
curl https://editor.p5js.org/editor/projects/erHP1oZMO/zip -o "downloads/zips/video-tint-2x2-mobile.zip"
curl https://editor.p5js.org/editor/projects/NLVK9ZI7a/zip -o "downloads/zips/W4: Re-write as a loop - I copy.zip"
curl https://editor.p5js.org/editor/projects/9xwd7Q-Re/zip -o "downloads/zips/W4: Re-write as a loop - III copy.zip"
curl https://editor.p5js.org/editor/projects/0aB9AAgQt/zip -o "downloads/zips/Week 2 homework V1 copy copy copy.zip"
curl https://editor.p5js.org/editor/projects/zzhlY9VFr/zip -o "downloads/zips/week01 demo.zip"
curl https://editor.p5js.org/editor/projects/bEetf-BC6/zip -o "downloads/zips/week2, animation copy.zip"
curl https://editor.p5js.org/editor/projects/Vu5Sesf0Q/zip -o "downloads/zips/Week3 homework - V3 copy.zip"
curl https://editor.p5js.org/editor/projects/P0MCy2a6Z/zip -o "downloads/zips/Wide afrovenator.zip"
curl https://editor.p5js.org/editor/projects/xYjreHHtl/zip -o "downloads/zips/WK2 move a circle with random size copy.zip"
curl https://editor.p5js.org/editor/projects/epi9TNVnh/zip -o "downloads/zips/wk2-sketch copy.zip"
curl https://editor.p5js.org/editor/projects/B6L5fhfSn/zip -o "downloads/zips/Wk4 hw1 copy.zip"