curl https://editor.p5js.org/editor/projects/7hzeHDSIl/zip -o "downloads/zips/03-jht-hatviz.zip"
curl https://editor.p5js.org/editor/projects/J7Zhes2Tc/zip -o "downloads/zips/11.4: Brightness getpixel.zip"
curl https://editor.p5js.org/editor/projects/IwaHqYnDn/zip -o "downloads/zips/7.3 Arrays of objects 1 copy.zip"
curl https://editor.p5js.org/editor/projects/wOBMJbldS/zip -o "downloads/zips/Acceleration Ball Bounce.zip"
curl https://editor.p5js.org/editor/projects/Rdb_xgkkW/zip -o "downloads/zips/acceleration-scope.zip"
curl https://editor.p5js.org/editor/projects/ncIe7u-WC/zip -o "downloads/zips/Firebase-createImg-board copy.zip"
curl https://editor.p5js.org/editor/projects/G4K2yaPnz/zip -o "downloads/zips/IMS - Truchet Vamoss copy.zip"
curl https://editor.p5js.org/editor/projects/CYMdD77ySc/zip -o "downloads/zips/ims-03-jht truchet tiles pause copy.zip"
curl https://editor.p5js.org/editor/projects/3VKJ-q8ar/zip -o "downloads/zips/ims03-jht scrolling color bars.zip"
curl https://editor.p5js.org/editor/projects/ZGUqiovgG/zip -o "downloads/zips/ims03-jht scrolling color time.zip"
curl https://editor.p5js.org/editor/projects/MbS5C3j-F/zip -o "downloads/zips/Necessary-forgery-timed-drawing.zip"
curl https://editor.p5js.org/editor/projects/4DETmJP-l/zip -o "downloads/zips/Outstanding fortnight.zip"
curl https://editor.p5js.org/editor/projects/lNRQmapgz/zip -o "downloads/zips/Rainbow Canvas.zip"
curl https://editor.p5js.org/editor/projects/G6Zr5SBuq/zip -o "downloads/zips/rotationX.zip"
curl https://editor.p5js.org/editor/projects/TXvXSJY6L/zip -o "downloads/zips/rotationXYZ.zip"
curl https://editor.p5js.org/editor/projects/oVJEGvodF/zip -o "downloads/zips/Simple Draw.zip"
curl https://editor.p5js.org/editor/projects/hw8qkUuAw/zip -o "downloads/zips/Slit Scan copy.zip"
curl https://editor.p5js.org/editor/projects/-t2O5JfBr/zip -o "downloads/zips/timed-drawing.zip"
curl https://editor.p5js.org/editor/projects/yEhwOiog5/zip -o "downloads/zips/timed-drawing-class.zip"
curl https://editor.p5js.org/editor/projects/lBrb1cBQ7/zip -o "downloads/zips/truchet tiles copy.zip"
curl https://editor.p5js.org/editor/projects/ghy_WpWDr/zip -o "downloads/zips/truchet tiles odd.zip"
curl https://editor.p5js.org/editor/projects/fWSv5uzke/zip -o "downloads/zips/truchet tiles pause copy.zip"
curl https://editor.p5js.org/editor/projects/1CpIVSqp_d/zip -o "downloads/zips/truchet tiles tweeked.zip"
curl https://editor.p5js.org/editor/projects/aJkcqKahg/zip -o "downloads/zips/video meter rgb long.zip"
curl https://editor.p5js.org/editor/projects/_0fWGg7ni/zip -o "downloads/zips/video meter rgb tall.zip"
curl https://editor.p5js.org/editor/projects/sJM2AMf5T/zip -o "downloads/zips/video pixel.zip"
curl https://editor.p5js.org/editor/projects/p0ato8vra/zip -o "downloads/zips/video pixel meter.zip"
curl https://editor.p5js.org/editor/projects/HRjZBETUA/zip -o "downloads/zips/video pixel scan.zip"
curl https://editor.p5js.org/editor/projects/3ZwzK2buW/zip -o "downloads/zips/video pixel scan random.zip"
curl https://editor.p5js.org/editor/projects/erHP1oZMO/zip -o "downloads/zips/video-tint-2x2-mobile.zip"
curl https://editor.p5js.org/editor/projects/xYjreHHtl/zip -o "downloads/zips/WK2 move a circle with random size copy.zip"